name: BuildAndTest

on:
  push:
    branches:
      - main

jobs:
  buildAndTest:
    uses: sp0rk/chaffinch-gha/.github/workflows/buildAndTest.yml@main
    secrets:
      jitPackToken: ""
    with:
      coverageBadge: true
      coverageReport: false

  ktlint:
    uses: sp0rk/chaffinch-gha/.github/workflows/lint.yml@main
    secrets:
      REVIEWDOG_TOKEN: ${{secrets.GITHUB_TOKEN}}
    with:
      failOnError: true
      reporter: "github-check"